# Listen on this internface:port
listen: 127.0.0.1:8080

# Refresh repodata.json after 100 days
max_age_minutes: 144000

# Allow these channels and subdirs
channels:
  conda-forge:
    subdirs:
      - linux-64
      - linux-aarch64
      - osx-64
      - osx-arm64
      - win-64
      - win-arm64
      - noarch
    # Allow these package names (all versions) in this channel
    # Comment out to allow all packages
    # This contains all package names in conda-forge on 2023-08-05
    allowlist_file: conda-forge-20230805.txt
